package com.corejava.CarDemo;

// Generated by Copilot - start
public abstract class Car implements Drive {

    private String brand;
    private String model;
    private int year;
    private String color;
    private int currentSpeed;

    public Car(String brand, String model, int year, String color) {
        this.brand = brand;
        this.model = model;
        this.year = year;
        this.color = color;
        this.currentSpeed = 0;
    }

    public String getBrand() {
        return brand;
    }

    public String getModel() {
        return model;
    }

    public int getYear() {
        return year;
    }

    public String getColor() {
        return color;
    }

    public int getCurrentSpeed() {
        return currentSpeed;
    }

    @Override
    public void accelerate(int speed) {
        this.currentSpeed += speed;
        System.out.println(brand + " " + model + " accelerating. Current speed: " + this.currentSpeed + " km/h");
    }

    @Override
    public void brake() {
        if (this.currentSpeed > 0) {
            this.currentSpeed = Math.max(0, this.currentSpeed - 20);
        }
        System.out.println(brand + " " + model + " braking. Current speed: " + this.currentSpeed + " km/h");
    }

    @Override
    public void steer(String direction) {
        System.out.println(brand + " " + model + " steering " + direction);
    }

    public abstract String getFuelType();

    @Override
    public String toString() {
        return year + " " + brand + " " + model + " [" + color + "] - Fuel: " + getFuelType();
    }
}
// Generated by Copilot - end
// Timestamp: 2026-03-10T17:15:17Z
