package com.corejava.CarDemo;

// Generated by Copilot - start
public interface Drive {

    void accelerate(int speed);

    void brake();

    void steer(String direction);

    String getDriveInfo();
}
// Generated by Copilot - end
// Timestamp: 2026-03-10T17:15:17Z
