package com.corejava.CarDemo;

import java.util.ArrayList;
import java.util.List;

// Generated by Copilot - start
public class Main {

    public static void main(String[] args) {

        List<Car> cars = new ArrayList<>();

        Suzuki swift = new Suzuki("Swift", 2023, "Red", "VXi");
        Toyota camry = new Toyota("Camry", 2024, "Silver", true);
        Toyota corolla = new Toyota("Corolla", 2022, "White", false);
        Renault duster = new Renault("Duster", 2023, "Blue", "1.5L");
        Renault kwid = new Renault("Kwid", 2021, "Orange", "1.0L");

        cars.add(swift);
        cars.add(camry);
        cars.add(corolla);
        cars.add(duster);
        cars.add(kwid);

        System.out.println("========== Car Demo ==========");
        System.out.println();

        for (Car car : cars) {
            System.out.println(car);
            System.out.println("  Drive Info : " + car.getDriveInfo());
            car.accelerate(40);
            car.steer("left");
            car.brake();
            System.out.println();
        }

        System.out.println("========== Polymorphism via Drive interface ==========");
        System.out.println();

        List<Drive> driveables = new ArrayList<>(cars);
        for (Drive d : driveables) {
            System.out.println(d.getDriveInfo());
        }
    }
}
// Generated by Copilot - end
// Timestamp: 2026-03-10T17:15:17Z
