package com.corejava.CarDemo;

// Generated by Copilot - start
public class Renault extends Car {

    private String engineSize;

    public Renault(String model, int year, String color, String engineSize) {
        super("Renault", model, year, color);
        this.engineSize = engineSize;
    }

    @Override
    public String getFuelType() {
        return "Diesel";
    }

    @Override
    public String getDriveInfo() {
        return "Renault " + getModel() + " (" + engineSize + ") - European & dynamic drive";
    }

    public String getEngineSize() {
        return engineSize;
    }
}
// Generated by Copilot - end
// Timestamp: 2026-03-10T17:15:17Z
