package com.corejava.CarDemo;

// Generated by Copilot - start
public class Suzuki extends Car {

    private String variant;

    public Suzuki(String model, int year, String color, String variant) {
        super("Suzuki", model, year, color);
        this.variant = variant;
    }

    @Override
    public String getFuelType() {
        return "Petrol";
    }

    @Override
    public String getDriveInfo() {
        return "Suzuki " + getModel() + " (" + variant + ") - Compact & fuel-efficient drive";
    }

    public String getVariant() {
        return variant;
    }
}
// Generated by Copilot - end
// Timestamp: 2026-03-10T17:15:17Z
