package com.corejava.CarDemo;

// Generated by Copilot - start
public class Toyota extends Car {

    private boolean isHybrid;

    public Toyota(String model, int year, String color, boolean isHybrid) {
        super("Toyota", model, year, color);
        this.isHybrid = isHybrid;
    }

    @Override
    public String getFuelType() {
        return isHybrid ? "Hybrid (Petrol/Electric)" : "Petrol";
    }

    @Override
    public String getDriveInfo() {
        return "Toyota " + getModel() + (isHybrid ? " [Hybrid]" : "") + " - Reliable & smooth drive";
    }

    public boolean isHybrid() {
        return isHybrid;
    }
}
// Generated by Copilot - end
// Timestamp: 2026-03-10T17:15:17Z
